site_name: Andreu
theme:
  name: 'material'
  custom_dir: 'docs/overrides'
  palette:
    primary: 'indigo'
    accent: 'pink'
    background: 'white'
    surface: 'grey'
    error: 'red'

extra_css:
  - 'overrides/extra.css'

nav:
  - Inicio: index.md
  - Articulos EDD:
    - Articulo 1: EDD/act_1.md
    - Articulo 2: EDD/act_2.md
    - Articulo 3: EDD/act_3.md
    - Articulo 4: EDD/act_4.md
    - Articulo 5: EDD/act_5.md
    - Articulo 6: EDD/act_6.md
    - Guia Git: EDD/guia_git.md
    - RSC:
      - Actividad 1: EDD/RSC/act1.md
      - Actividad 2: EDD/RSC/act2.md
      - Actividad 3: EDD/RSC/act3.md
    - Java with Ant: EDD/actividad_calculadora.md
    - Java with Maven: EDD/actividad_maven.md
  - Articulos LMI:
    - Articulo 1: LMI/act_1.md
    - Articulo 2: LMI/act_2.md
    - HTML:
      - Actividad 1: LMI/HTML/Act1.html
      - Actividad 2: LMI/HTML/Act2.html
      - Actividad 3: LMI/HTML/Act3.html
      - Actividad 4: LMI/HTML/Act4.html
      - Actividad 5: LMI/HTML/Act5.html
      - Actividad 6: LMI/HTML/Act6.html
      - Actividad 7: LMI/HTML/Act7.html
      - Actividad 8: LMI/HTML/Act8.html
      - Actividad 9: LMI/HTML/Act9.html
      - Actividad 10: LMI/HTML/Act10.html
      - Actividad 11: LMI/HTML/Act11.html
      - Actividad 12: LMI/HTML/Act12.html
      - Actividad 13: LMI/HTML/Act13.html
      - Actividad 14: LMI/HTML/Act14.html
      - Actividad 15: LMI/HTML/Act15.html
    - JavaScript:
      - Actividad 1: LMI/JavaScript/act1.js
      - Actividad 2: LMI/JavaScript/act2.js
      - Actividad 3: LMI/JavaScript/act3.js
      - Actividad 4: LMI/JavaScript/act4.js
      - Actividad 5: LMI/JavaScript/act5.js
      - Actividad 6: LMI/JavaScript/act6.js
      - Actividad 7: LMI/JavaScript/act7.js
      - Actividad 8: LMI/JavaScript/act8.js
      - Actividad 9: LMI/JavaScript/act9.js
      - Actividad 10: LMI/JavaScript/act10.js
      - Actividad 11: LMI/JavaScript/act11.js
      - Actividad 12: LMI/JavaScript/act12.js
    